name: '$(date:yyyyMMdd)$(rev:.r)'

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
- group: "PowerShell Gallery Sander"

steps:
- pwsh: |
    Import-Module ./Axinom.DevOpsTooling/Axinom.DevOpsTooling.psd1
    Write-Host 11111
    Set-PowerShellModuleMetadataBeforeBuild -path ./Axinom.DevOpsTooling/Axinom.DevOpsTooling.psd1
    Write-Host 22222
    Set-PowerShellModuleBuildString -path ./Axinom.DevOpsTooling/Axinom.DevOpsTooling.psd1
    Write-Host 33333
    Publish-Module -Path "$(Build.SourcesDirectory)/Axinom.DevOpsTooling" -NugetAPIKey "$(PsGalleryKey)"
    Write-Host 44444