name: '$(date:yyyyMMdd)$(rev:.r)'

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
- group: "PowerShell Gallery Sander"

steps:
- pwsh: |
    # Try fix the foreverhang in Publish-Module
    Install-PackageProvider Nuget –Force
    Install-Module –Name PowerShellGet –Force

    Import-Module ./Axinom.DevOpsTooling/Axinom.DevOpsTooling.psd1
    Set-PowerShellModuleMetadataBeforeBuild -path ./Axinom.DevOpsTooling/Axinom.DevOpsTooling.psd1
    Set-PowerShellModuleBuildString -path ./Axinom.DevOpsTooling/Axinom.DevOpsTooling.psd1
    # This can occasionally just hang, it seems.
    Publish-Module -Path "$(Build.SourcesDirectory)/Axinom.DevOpsTooling" -NugetAPIKey "$(PsGalleryKey)" -Verbose